# Name of your site (displayed in the header)
name: Aboubakar Moussa

# Short bio or description (displayed in the header)
description: Changing the world's networks, one Python script at a time

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/abakamousa/blog/blob/master/images/my_picture%20(2).jpg

# Includes an icon in the footer for each username you enter
footer-links:
  
  email: abakamousa@gmail.com
  github: abakamousa
  linkedin: aboubakar-moussa/
  twitter: abakamousa

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/blog"
